### ISSUE TITLE
Incorrect contract usage

### ISSUE THREAD

**Issue by Sxtanna** [playhexalite/stronghold#8]
These function contracts current use [`InvocationKind.EXACTLY_ONCE`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.contracts/-invocation-kind/-e-x-a-c-t-l-y_-o-n-c-e.html), which would imply they are 100% always called exactly one time within the function.

They should be marked with [`InvocationKind.AT_MOST_ONCE`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.contracts/-invocation-kind/-a-t_-m-o-s-t_-o-n-c-e.html), which implies that they can be called, and if they are, only once. _(which is the actual behavior of these functions)_

https://github.com/playhexalite/stronghold/blob/c6ec6e067823c0810e94ee281a5f5a6adc44b4c1/stronghold-data-common/src/commonMain/kotlin/org/hexalite/stronghold/data/functional/Either.kt#L84-L138

-----

This change would match to them their analog within the actual Kotlin [`Result`](https://github.com/JetBrains/kotlin/blob/master/libraries/stdlib/src/kotlin/util/Result.kt) type:
https://github.com/JetBrains/kotlin/blob/ea836fd46a1fef07d77c96f9d7e8d7807f793453/libraries/stdlib/src/kotlin/util/Result.kt#L178-L196

**Comment by Sxtanna** [comment]
Same can be said for these set of functions.

https://github.com/playhexalite/stronghold/blob/c6ec6e067823c0810e94ee281a5f5a6adc44b4c1/stronghold-data-common/src/commonMain/kotlin/org/hexalite/stronghold/data/functional/Either.kt#L149-L203

-----

The calling of the passed function is conditional on the state of the monad and is not guaranteed.

**Comment by FromSyntax** [comment]
It is a pretty silly mistake. Thank you for making us aware of that!

**Comment by FromSyntax** [comment]
I think everything is correct now
